# Generated by Django 4.2.9 on 2024-01-14 00:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("entries", "0003_entry_find_pattern"),
    ]

    operations = [
        migrations.AlterField(
            model_name="entry",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
